### ISSUE TITLE
Can you add the link to the website in the repo description?

### ISSUE THREAD

**Issue by shelbyspees** [mrice/lasc#3]
Example:

<img width="809" alt="screenshot 2015-10-10 15 58 02" src="https://cloud.githubusercontent.com/assets/5217772/10413673/b6ca61fa-6f67-11e5-9b55-fe07f62f4b5d.png">

**Comment by shelbyspees** [comment]
It's not super necessary but it feels emptry

**Comment by shelbyspees** [comment]
Oops clicked the wrong thing. It's not super necessary but it would make the repo feel more complete.

**Comment by mrice** [comment]
Cool, good idea. Will do once I get back to  real machine!

**Comment by mrice** [comment]
Thanks again. Done!
